var xhook=function(){"use strict";const e=(e,t)=>Array.prototype.slice.call(e,t);let t=null;"undefined"!=typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope?t=self:"undefined"!=typeof global?t=global:window&&(t=window);const n=t,o=t.document,r=["load","loadend","loadstart"],s=["progress","abort","error","timeout"],a=e=>["returnValue","totalSize","position"].includes(e),i=function(e,t){for(let n in e){if(a(n))continue;const o=e[n];try{t[n]=o}catch(e){}}return t},c=function(e,t,n){const o=e=>function(o){const r={};for(let e in o){if(a(e))continue;const s=o[e];r[e]=s===t?n:s}return n.dispatchEvent(e,r)};for(let r of Array.from(e))n._has(r)&&(t[`on${r}`]=o(r))},u=function(e){if(o&&null!=o.createEventObject){const t=o.createEventObject();return t.type=e,t}try{return new Event(e)}catch(t){return{type:e}}},l=function(t){let n={};const o=e=>n[e]||[],r={addEventListener:function(e,t,r){n[e]=o(e),n[e].indexOf(t)>=0||(r=void 0===r?n[e].length:r,n[e].splice(r,0,t))},removeEventListener:function(e,t){if(void 0===e)return void(n={});void 0===t&&(n[e]=[]);const r=o(e).indexOf(t);-1!==r&&o(e).splice(r,1)},dispatchEvent:function(){const n=e(arguments),s=n.shift();t||(n[0]=i(n[0],u(s)),Object.defineProperty(n[0],"target",{writable:!1,value:this}));const a=r[`on${s}`];a&&a.apply(r,n);const c=o(s).concat(o("*"));for(let e=0;e<c.length;e++){c[e].apply(r,n)}},_has:e=>!(!n[e]&&!r[`on${e}`])};return t&&(r.listeners=t=>e(o(t)),r.on=r.addEventListener,r.off=r.removeEventListener,r.fire=r.dispatchEvent,r.once=function(e,t){var n=function(){return r.off(e,n),t.apply(null,arguments)};return r.on(e,n)},r.destroy=()=>n={}),r};var f=function(e,t){switch(typeof e){case"object":return n=e,Object.entries(n).map((([e,t])=>`${e.toLowerCase()}: ${t}`)).join("\r\n");case"string":return function(e,t){const n=e.split("\r\n");null==t&&(t={});for(let e of n)if(/([^:]+):\s*(.+)/.test(e)){const e=null!=RegExp.$1?RegExp.$1.toLowerCase():void 0,n=RegExp.$2;null==t[e]&&(t[e]=n)}return t}(e,t)}var n;return[]};const d=l(!0),p=e=>void 0===e?null:e,h=n.XMLHttpRequest,y=function(){const e=new h,t={};let n,o,a,u=null;var y=0;const v=function(){if(a.status=u||e.status,-1!==u&&(a.statusText=e.statusText),-1===u);else{const t=f(e.getAllResponseHeaders());for(let e in t){const n=t[e];if(!a.headers[e]){const t=e.toLowerCase();a.headers[t]=n}}}},b=function(){x.status=a.status,x.statusText=a.statusText},g=function(){n||x.dispatchEvent("load",{}),x.dispatchEvent("loadend",{}),n&&(x.readyState=0)},E=function(e){for(;e>y&&y<4;)x.readyState=++y,1===y&&x.dispatchEvent("loadstart",{}),2===y&&b(),4===y&&(b(),"text"in a&&(x.responseText=a.text),"xml"in a&&(x.responseXML=a.xml),"data"in a&&(x.response=a.data),"finalUrl"in a&&(x.responseURL=a.finalUrl)),x.dispatchEvent("readystatechange",{}),4===y&&(!1===t.async?g():setTimeout(g,0))},m=function(e){if(4!==e)return void E(e);const n=d.listeners("after");var o=function(){if(n.length>0){const e=n.shift();2===e.length?(e(t,a),o()):3===e.length&&t.async?e(t,a,o):o()}else E(4)};o()};var x=l();t.xhr=x,e.onreadystatechange=function(t){try{2===e.readyState&&v()}catch(e){}4===e.readyState&&(o=!1,v(),function(){if(e.responseType&&"text"!==e.responseType)"document"===e.responseType?(a.xml=e.responseXML,a.data=e.responseXML):a.data=e.response;else{a.text=e.responseText,a.data=e.responseText;try{a.xml=e.responseXML}catch(e){}}"responseURL"in e&&(a.finalUrl=e.responseURL)}()),m(e.readyState)};const w=function(){n=!0};x.addEventListener("error",w),x.addEventListener("timeout",w),x.addEventListener("abort",w),x.addEventListener("progress",(function(t){y<3?m(3):e.readyState<=3&&x.dispatchEvent("readystatechange",{})})),"withCredentials"in e&&(x.withCredentials=!1),x.status=0;for(let e of Array.from(s.concat(r)))x[`on${e}`]=null;if(x.open=function(e,r,s,i,c){y=0,n=!1,o=!1,t.headers={},t.headerNames={},t.status=0,t.method=e,t.url=r,t.async=!1!==s,t.user=i,t.pass=c,a={},a.headers={},m(1)},x.send=function(n){let u,l;for(u of["type","timeout","withCredentials"])l="type"===u?"responseType":u,l in x&&(t[u]=x[l]);t.body=n;const f=d.listeners("before");var p=function(){if(!f.length)return function(){for(u of(c(s,e,x),x.upload&&c(s.concat(r),e.upload,x.upload),o=!0,e.open(t.method,t.url,t.async,t.user,t.pass),["type","timeout","withCredentials"]))l="type"===u?"responseType":u,u in t&&(e[l]=t[u]);for(let n in t.headers){const o=t.headers[n];n&&e.setRequestHeader(n,o)}e.send(t.body)}();const n=function(e){if("object"==typeof e&&("number"==typeof e.status||"number"==typeof a.status))return i(e,a),"data"in e||(e.data=e.response||e.text),void m(4);p()};n.head=function(e){i(e,a),m(2)},n.progress=function(e){i(e,a),m(3)};const d=f.shift();1===d.length?n(d(t)):2===d.length&&t.async?d(t,n):n()};p()},x.abort=function(){u=-1,o?e.abort():x.dispatchEvent("abort",{})},x.setRequestHeader=function(e,n){const o=null!=e?e.toLowerCase():void 0,r=t.headerNames[o]=t.headerNames[o]||e;t.headers[r]&&(n=t.headers[r]+", "+n),t.headers[r]=n},x.getResponseHeader=e=>p(a.headers[e?e.toLowerCase():void 0]),x.getAllResponseHeaders=()=>p(f(a.headers)),e.overrideMimeType&&(x.overrideMimeType=function(){e.overrideMimeType.apply(e,arguments)}),e.upload){let e=l();x.upload=e,t.upload=e}return x.UNSENT=0,x.OPENED=1,x.HEADERS_RECEIVED=2,x.LOADING=3,x.DONE=4,x.response="",x.responseText="",x.responseXML=null,x.readyState=0,x.statusText="",x};y.UNSENT=0,y.OPENED=1,y.HEADERS_RECEIVED=2,y.LOADING=3,y.DONE=4;var v={patch(){h&&(n.XMLHttpRequest=y)},unpatch(){h&&(n.XMLHttpRequest=h)},Native:h,Xhook:y};function b(e,t,n,o){return new(n||(n=Promise))((function(r,s){function a(e){try{c(o.next(e))}catch(e){s(e)}}function i(e){try{c(o.throw(e))}catch(e){s(e)}}function c(e){var t;e.done?r(e.value):(t=e.value,t instanceof n?t:new n((function(e){e(t)}))).then(a,i)}c((o=o.apply(e,t||[])).next())}))}const g=n.fetch;function E(e){return e instanceof Headers?m([...e.entries()]):Array.isArray(e)?m(e):e}function m(e){return e.reduce(((e,[t,n])=>(e[t]=n,e)),{})}const x=function(e,t={headers:{}}){let n=Object.assign(Object.assign({},t),{isFetch:!0});if(e instanceof Request){const o=function(e){let t={};return["method","headers","body","mode","credentials","cache","redirect","referrer","referrerPolicy","integrity","keepalive","signal","url"].forEach((n=>t[n]=e[n])),t}(e),r=Object.assign(Object.assign({},E(o.headers)),E(n.headers));n=Object.assign(Object.assign(Object.assign({},o),t),{headers:r,acceptedRequest:!0})}else n.url=e;const o=d.listeners("before"),r=d.listeners("after");return new Promise((function(t,s){let a=t;const i=function(e){if(!r.length)return a(e);const t=r.shift();return 2===t.length?(t(n,e),i(e)):3===t.length?t(n,e,i):i(e)},c=function(e){if(void 0!==e){const n=new Response(e.body||e.text,e);return t(n),void i(n)}u()},u=function(){if(!o.length)return void l();const e=o.shift();return 1===e.length?c(e(n)):2===e.length?e(n,c):void 0},l=()=>b(this,void 0,void 0,(function*(){const{url:t,isFetch:o,acceptedRequest:r}=n,c=function(e,t){var n={};for(var o in e)Object.prototype.hasOwnProperty.call(e,o)&&t.indexOf(o)<0&&(n[o]=e[o]);if(null!=e&&"function"==typeof Object.getOwnPropertySymbols){var r=0;for(o=Object.getOwnPropertySymbols(e);r<o.length;r++)t.indexOf(o[r])<0&&Object.prototype.propertyIsEnumerable.call(e,o[r])&&(n[o[r]]=e[o[r]])}return n}(n,["url","isFetch","acceptedRequest"]);return e instanceof Request&&c.body instanceof ReadableStream&&(c.body=yield new Response(c.body).text()),g(t,c).then((e=>i(e))).catch((function(e){return a=s,i(e),s(e)}))}));u()}))};var w={patch(){g&&(n.fetch=x)},unpatch(){g&&(n.fetch=g)},Native:g,Xhook:x};const O=d;return O.EventEmitter=l,O.before=function(e,t){if(e.length<1||e.length>2)throw"invalid hook";return O.on("before",e,t)},O.after=function(e,t){if(e.length<2||e.length>3)throw"invalid hook";return O.on("after",e,t)},O.enable=function(){v.patch(),w.patch()},O.disable=function(){v.unpatch(),w.unpatch()},O.XMLHttpRequest=v.Native,O.fetch=w.Native,O.headers=f,O.enable(),O}();

dt = JSON.stringify([
  {
    "id": 981540,
    "endMonth": 5,
    "endTermId": 0,
    "endYear": 2025,
    "termTypeId": 0,
    "instanceId": 6383,
    "startMonth": 8,
    "startTermId": 0,
    "startYear": 2022,
    "isAcademicUpdate": null,
    "graduated": false,
    "primaryCollege": null,
    "profile": null,
    "code": "1669",
    "name": "Mercer University",
    "type": "Undergraduate",
    "degreeObtained": "in progress",
    "country": "United States of America (the)",
    "createdDate": 1727308800000,
    "updatedDate": 1727827200000,
    "terms": [
      {
        "id": 5513089,
        "termId": 0,
        "term": "1st Semester (Fall)",
        "yearId": 0,
        "year": "2022",
        "academicStatusId": 0,
        "academicStatus": null,
        "termInProgress": null,
        "courses": [
          {
            "id": 23854979,
            "code": "REL 110",
            "title": "Why Religion Matters",
            "subjectId": 0,
            "subject": "Philosophy/Religion",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23854980,
            "code": null,
            "title": "AP Credit: Statistics",
            "subjectId": 0,
            "subject": "Math",
            "credits": "3.00",
            "grade": "P",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23854981,
            "code": "UNV 101",
            "title": "First-Year Student Experience",
            "subjectId": 0,
            "subject": "Other",
            "credits": "1.00",
            "grade": "P",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23854982,
            "code": null,
            "title": "AP Credit: Biology",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "9.00",
            "grade": "P",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23854983,
            "code": null,
            "title": "AP Credit: Computer Science A",
            "subjectId": 0,
            "subject": "Computer Science/Technology",
            "credits": "4.00",
            "grade": "P",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23854984,
            "code": null,
            "title": "AP Credit: Calculus BC",
            "subjectId": 0,
            "subject": "Math",
            "credits": "4.00",
            "grade": "P",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23854985,
            "code": null,
            "title": "AP Credit: Physics 2",
            "subjectId": 0,
            "subject": "Physics",
            "credits": "4.00",
            "grade": "P",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23854986,
            "code": null,
            "title": "AP Credit: Language & Composition",
            "subjectId": 0,
            "subject": "English Language & Literature",
            "credits": "4.00",
            "grade": "P",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23854987,
            "code": null,
            "title": "AP Credit: Calculus AB",
            "subjectId": 0,
            "subject": "Math",
            "credits": "4.00",
            "grade": "P",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23854988,
            "code": null,
            "title": "AP Credit: Physics 1",
            "subjectId": 0,
            "subject": "Physics",
            "credits": "4.00",
            "grade": "P",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23854991,
            "code": null,
            "title": "AP Credit: Chemistry",
            "subjectId": 0,
            "subject": "Chemistry",
            "credits": "8.00",
            "grade": "P",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23854989,
            "code": "CHM 221",
            "title": "Organic Chemistry I",
            "subjectId": 0,
            "subject": "Chemistry",
            "credits": "4.00",
            "grade": "B",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "4.0",
            "courseClassification": null
          },
          {
            "id": 23854990,
            "code": "PSY 101",
            "title": "Introduction to Psychology",
            "subjectId": 0,
            "subject": "Behavioral & Social Sciences",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23854992,
            "code": "BIO 212",
            "title": "Introduction to Biology II",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "5.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "5.0",
            "courseClassification": null
          }
        ],
        "isVerified": null,
        "auEnabled": null,
        "termCreatedDate": null,
        "isPrerequisite": null,
        "typeAccepted": null
      },
      {
        "id": 5513093,
        "termId": 0,
        "term": "2nd Semester (Spring)",
        "yearId": 0,
        "year": "2022",
        "academicStatusId": 0,
        "academicStatus": null,
        "termInProgress": null,
        "courses": [
          {
            "id": 23855012,
            "code": "BIO 310",
            "title": "Genetics",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "4.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "4.0",
            "courseClassification": null
          },
          {
            "id": 23855013,
            "code": "CHM 222",
            "title": "Organic Chemistry II",
            "subjectId": 0,
            "subject": "Chemistry",
            "credits": "4.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "4.0",
            "courseClassification": null
          },
          {
            "id": 23855011,
            "code": "INT 301",
            "title": "Understanding Russia Through Literature",
            "subjectId": 0,
            "subject": "English Language & Literature",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23855015,
            "code": "FRE 301",
            "title": "Advanced Reading and Composition",
            "subjectId": 0,
            "subject": "Foreign Languages & Literature",
            "credits": "0.00",
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23855014,
            "code": "CHM 241",
            "title": "Quantitative Analysis",
            "subjectId": 0,
            "subject": "Chemistry",
            "credits": "4.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "4.0",
            "courseClassification": null
          }
        ],
        "isVerified": null,
        "auEnabled": null,
        "termCreatedDate": null,
        "isPrerequisite": null,
        "typeAccepted": null
      },
      {
        "id": 5513091,
        "termId": 0,
        "term": "1st Semester (Fall)",
        "yearId": 0,
        "year": "2023",
        "academicStatusId": 0,
        "academicStatus": null,
        "termInProgress": null,
        "courses": [
          {
            "id": 23855017,
            "code": "BIO 435",
            "title": "Neurobiology",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23855018,
            "code": "BIO 475",
            "title": "Virology",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "4.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "4.0",
            "courseClassification": null
          },
          {
            "id": 23855016,
            "code": "CHM 330",
            "title": "Physical Chemistry",
            "subjectId": 0,
            "subject": "Chemistry",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23855020,
            "code": "PHI 265",
            "title": "Philosophy and Film",
            "subjectId": 0,
            "subject": "Philosophy/Religion",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23855019,
            "code": "BMB 465",
            "title": "Biochemistry I",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          }
        ],
        "isVerified": null,
        "auEnabled": null,
        "termCreatedDate": null,
        "isPrerequisite": null,
        "typeAccepted": null
      },
      {
        "id": 5513090,
        "termId": 0,
        "term": "2nd Semester (Spring)",
        "yearId": 0,
        "year": "2023",
        "academicStatusId": 0,
        "academicStatus": null,
        "termInProgress": null,
        "courses": [
          {
            "id": 23854993,
            "code": "BIO 410",
            "title": "Molecular Genetics",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "4.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "4.0",
            "courseClassification": null
          },
          {
            "id": 23854995,
            "code": "BIO 482",
            "title": "Immunology",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23854994,
            "code": "BMB 466",
            "title": "Biochemistry II",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23854998,
            "code": "BIO 299",
            "title": "Research in Biology",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "1.00",
            "grade": "P",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23854997,
            "code": "MAT 345",
            "title": "Applied Mathematical Modeling",
            "subjectId": 0,
            "subject": "Math",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23854999,
            "code": "BMB 467",
            "title": "Biochemistry & Molecular Biology Capstone Laboratory",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "2.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "2.0",
            "courseClassification": null
          }
        ],
        "isVerified": null,
        "auEnabled": null,
        "termCreatedDate": null,
        "isPrerequisite": null,
        "typeAccepted": null
      },
      {
        "id": 5513095,
        "termId": 0,
        "term": "Summer Semester (Summer)",
        "yearId": 0,
        "year": "2024",
        "academicStatusId": 0,
        "academicStatus": null,
        "termInProgress": null,
        "courses": [
          {
            "id": 23855007,
            "code": "EGR 291",
            "title": "Biomech, Design & Clin Fit Prostetics for up& low knee ",
            "subjectId": 0,
            "subject": "Engineering",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23855008,
            "code": "EGR 292",
            "title": "Instrument of Fitting Upper&Lower Extremity Prostheses",
            "subjectId": 0,
            "subject": "Engineering",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          }
        ],
        "isVerified": null,
        "auEnabled": null,
        "termCreatedDate": null,
        "isPrerequisite": null,
        "typeAccepted": null
      },
      {
        "id": 5513092,
        "termId": 0,
        "term": "1st Semester (Fall)",
        "yearId": 0,
        "year": "2024",
        "academicStatusId": 0,
        "academicStatus": null,
        "termInProgress": null,
        "courses": [
          {
            "id": 23855021,
            "code": "BMB 499",
            "title": "Senior Research in Biochemistry",
            "subjectId": 0,
            "subject": "Biology",
            "credits": null,
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23855022,
            "code": "BIO 430",
            "title": "Cancer Biology",
            "subjectId": 0,
            "subject": "Biology",
            "credits": null,
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23855023,
            "code": "BIO 301",
            "title": "Introduction to Vertebrate Zoology",
            "subjectId": 0,
            "subject": "Biology",
            "credits": null,
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23855024,
            "code": "MAT 350",
            "title": "College Geometry",
            "subjectId": 0,
            "subject": "Math",
            "credits": null,
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23855025,
            "code": "ANT 101",
            "title": "Introduction to Anthropology",
            "subjectId": 0,
            "subject": "Behavioral & Social Sciences",
            "credits": null,
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23855026,
            "code": "CSC 212",
            "title": "Programming Team Strategies",
            "subjectId": 0,
            "subject": "Computer Science/Technology",
            "credits": null,
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23855027,
            "code": "BIO 370",
            "title": "Principles of Ecology",
            "subjectId": 0,
            "subject": "Biology",
            "credits": null,
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23855028,
            "code": "MAT 350",
            "title": "College Geometry",
            "subjectId": 0,
            "subject": "Math",
            "credits": null,
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          }
        ],
        "isVerified": null,
        "auEnabled": null,
        "termCreatedDate": null,
        "isPrerequisite": null,
        "typeAccepted": null
      },
      {
        "id": 5513094,
        "termId": 0,
        "term": "2nd Semester (Spring)",
        "yearId": 0,
        "year": "2024",
        "academicStatusId": 0,
        "academicStatus": null,
        "termInProgress": null,
        "courses": [
          {
            "id": 23855000,
            "code": "BIO 460L",
            "title": "Eukaryotic Cell Biology Lab",
            "subjectId": 0,
            "subject": "Biology",
            "credits": null,
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23855001,
            "code": "CSC 310",
            "title": "File Structures & Advanced Algorithms",
            "subjectId": 0,
            "subject": "Computer Science/Technology",
            "credits": null,
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23855002,
            "code": "BIO 415",
            "title": "Bioinformatics",
            "subjectId": 0,
            "subject": "Biology",
            "credits": null,
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23855003,
            "code": "SOC 101",
            "title": "Introduction to Sociology",
            "subjectId": 0,
            "subject": "Behavioral & Social Sciences",
            "credits": null,
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23855004,
            "code": "BIO 389",
            "title": "Biology and Society",
            "subjectId": 0,
            "subject": "Biology",
            "credits": null,
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23855005,
            "code": "BIO 460",
            "title": "Eukaryotic Cell Biology",
            "subjectId": 0,
            "subject": "Biology",
            "credits": null,
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          },
          {
            "id": 23855006,
            "code": "MAT 326",
            "title": "Graph Theory and Combinatorics",
            "subjectId": 0,
            "subject": "Math",
            "credits": null,
            "grade": null,
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "courseClassification": null
          }
        ],
        "isVerified": null,
        "auEnabled": null,
        "termCreatedDate": null,
        "isPrerequisite": null,
        "typeAccepted": null
      }
    ]
  },
  {
    "id": 981541,
    "endMonth": 5,
    "endTermId": 0,
    "endYear": 2022,
    "termTypeId": 0,
    "instanceId": 6383,
    "startMonth": 5,
    "startTermId": 0,
    "startYear": 2020,
    "isAcademicUpdate": null,
    "graduated": true,
    "primaryCollege": null,
    "profile": null,
    "code": "1637",
    "name": "Georgia State University",
    "type": "Undergraduate",
    "degreeObtained": "no",
    "country": "United States of America (the)",
    "createdDate": 1727308800000,
    "updatedDate": 1727827200000,
    "terms": [
      {
        "id": 5513100,
        "termId": 0,
        "term": "Summer Semester (Summer)",
        "yearId": 0,
        "year": "2020",
        "academicStatusId": 0,
        "academicStatus": null,
        "termInProgress": null,
        "courses": [
          {
            "id": 23855045,
            "code": "ECON 2105",
            "title": "Principles of Macroeconomics",
            "subjectId": 0,
            "subject": "Behavioral & Social Sciences",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23855046,
            "code": "HIST 2110",
            "title": "Survey of U.S. History",
            "subjectId": 0,
            "subject": "History",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          }
        ],
        "isVerified": null,
        "auEnabled": null,
        "termCreatedDate": null,
        "isPrerequisite": null,
        "typeAccepted": null
      },
      {
        "id": 5513099,
        "termId": 0,
        "term": "1st Semester (Fall)",
        "yearId": 0,
        "year": "2020",
        "academicStatusId": 0,
        "academicStatus": null,
        "termInProgress": null,
        "courses": [
          {
            "id": 23855034,
            "code": "MATH 2420",
            "title": "Discrete Mathematics",
            "subjectId": 0,
            "subject": "Math",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          }
        ],
        "isVerified": null,
        "auEnabled": null,
        "termCreatedDate": null,
        "isPrerequisite": null,
        "typeAccepted": null
      },
      {
        "id": 5513096,
        "termId": 0,
        "term": "2nd Semester (Spring)",
        "yearId": 0,
        "year": "2020",
        "academicStatusId": 0,
        "academicStatus": null,
        "termInProgress": null,
        "courses": [
          {
            "id": 23855035,
            "code": "BIOL 2110",
            "title": "Human Anatomy and Physiology I",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23855036,
            "code": "BIOL 2110L",
            "title": "Human Anatomy & Physiology I Lab",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "1.00",
            "grade": "B",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "1.0",
            "courseClassification": null
          }
        ],
        "isVerified": null,
        "auEnabled": null,
        "termCreatedDate": null,
        "isPrerequisite": null,
        "typeAccepted": null
      },
      {
        "id": 5513097,
        "termId": 0,
        "term": "1st Semester (Fall)",
        "yearId": 0,
        "year": "2021",
        "academicStatusId": 0,
        "academicStatus": null,
        "termInProgress": null,
        "courses": [
          {
            "id": 23855029,
            "code": "BIOL 2120L",
            "title": "Human Anatomy & Physiology II Lab",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "1.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "1.0",
            "courseClassification": null
          },
          {
            "id": 23855028,
            "code": "BIOL 2300",
            "title": "Microbiology & Public Health",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23855032,
            "code": "BIOL 2310",
            "title": "Fundamental Microbiology Lab",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "1.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "1.0",
            "courseClassification": null
          },
          {
            "id": 23855031,
            "code": "BIOL 2120",
            "title": "Human Anatomy & Physiology II",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23855030,
            "code": "MATH 2641",
            "title": "Linear Algebra I",
            "subjectId": 0,
            "subject": "Math",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23855033,
            "code": "MATH 2215",
            "title": "Multivariate Calculus",
            "subjectId": 0,
            "subject": "Math",
            "credits": "4.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "4.0",
            "courseClassification": null
          }
        ],
        "isVerified": null,
        "auEnabled": null,
        "termCreatedDate": null,
        "isPrerequisite": null,
        "typeAccepted": null
      },
      {
        "id": 5513098,
        "termId": 0,
        "term": "2nd Semester (Spring)",
        "yearId": 0,
        "year": "2021",
        "academicStatusId": 0,
        "academicStatus": null,
        "termInProgress": null,
        "courses": [
          {
            "id": 23855037,
            "code": "BIOL 2107L",
            "title": "Principles of Biology I Lab",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "1.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "1.0",
            "courseClassification": null
          },
          {
            "id": 23855038,
            "code": "ENGL 1102",
            "title": "English Composition II",
            "subjectId": 0,
            "subject": "English Language & Literature",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23855039,
            "code": "MATH 2652",
            "title": "Differential Equations",
            "subjectId": 0,
            "subject": "Math",
            "credits": "4.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "4.0",
            "courseClassification": null
          },
          {
            "id": 23855040,
            "code": "PHYS 2211",
            "title": "Principles of Physics I",
            "subjectId": 0,
            "subject": "Physics",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23855042,
            "code": "BIOL 2107",
            "title": "Principles of Biology I",
            "subjectId": 0,
            "subject": "Biology",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23855041,
            "code": "CHEM 1212L",
            "title": "Principles of Chemistry II Lab",
            "subjectId": 0,
            "subject": "Chemistry",
            "credits": "1.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "1.0",
            "courseClassification": null
          },
          {
            "id": 23855044,
            "code": "CHEM 1212",
            "title": "Principles of Chemistry II",
            "subjectId": 0,
            "subject": "Chemistry",
            "credits": "3.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "3.0",
            "courseClassification": null
          },
          {
            "id": 23855043,
            "code": "PHYS 2211L",
            "title": "Principles of Physics I Lab",
            "subjectId": 0,
            "subject": "Physics",
            "credits": "1.00",
            "grade": "A",
            "convertedGrade": null,
            "auEnabled": null,
            "courseCreatedDate": null,
            "creditsDropDown": null,
            "isPrerequisite": null,
            "termId": null,
            "isScience": null,
            "subjectKey": null,
            "totalCourseUnit": null,
            "source": null,
            "geCourseCode": null,
            "transferable": null,
            "semesterHours": "1.0",
            "courseClassification": null
          }
        ],
        "isVerified": null,
        "auEnabled": null,
        "termCreatedDate": null,
        "isPrerequisite": null,
        "typeAccepted": null
      }
    ]
  }
]);

xhook.after(function (request, response) {
  console.log(request)
  console.log(response)
  if (request.url.endsWith("/colleges")) {
    console.log("CL")
    response.text = dt
    response.data = dt
  }
});

xhook.after(function (request, response) {
  if (request.url.endsWith("/prerequisites")) {
    u = JSON.parse(response.data)
    
    u.prerequisites.forEach(x => {
        console.log(x)
        x.course.forEach((y, i, a) => {
            if (y.collegeName == "Mercer University" && y.courseCode != "CHM 221" && y.grade != "P") {
                a[i].grade = "A"
            }
        })
        console.log(x)
    })
    
    console.log(u)
    response.data = JSON.stringify(u)
    response.text = JSON.stringify(u)
  }
});
